Beacon scanning
MakeSchool-Companion-App/Companion-Android pull request #2
Opened 2018-10-24 20:12 UTC by SlickJohnson

2018-10-24 20:50 UTC, LinnierGames requested changes
@SlickJohnson so I noticed the 18k addition to this PR. Most commonly, I was looking for tracked dependancy files, but I don't see that.

Are the 18k additions part of the set up of react native?

2018-10-24 22:46 UTC, SlickJohnson commented
@LinnierGames Yep, just react native. Removed node_modules in my first commit of this branch and I'm not using any other dependency managers.

2018-10-25 04:39 UTC, LinnierGames approved these changes

2018-10-25 10:27 UTC, jakeTran42 approved these changes
Not any issue I can find so far

2018-10-25 23:27 UTC, merged